exports.menu = [
    {
        "id":"1",
        "name":"首页",
        "type":"menu",
        "icon":"dashboard",
        "link":"/home",
        "serviceUrl":"/home",
        "description":"首页"
    },
    {
        "id":"2",
        "name":"权限管理",
        "type":"menu",
        "icon":"lock",
        "link":"/permission",
        "serviceUrl":"/permission",
        "description":"权限管理",
        "children":[
            {
                "id":"3",
                "parentId":"2",
                "name":"用户管理",
                "type":"menu",
                "link":"/user",
                "serviceUrl":"/user/queryUser",
                "description":"用户管理",
                "children":[
                    {
                        "id":"6",
                        "parentId":"3",
                        "name":"添加",
                        "type":"button",
                        "link":"addUser",
                        "serviceUrl":"/user/addUser",
                        "description":"添加"
                    },
                    {
                        "id":"7",
                        "parentId":"3",
                        "name":"编辑",
                        "type":"button",
                        "link":"editUser",
                        "serviceUrl":"/user/editUser",
                        "description":"编辑"
                    },
                    {
                        "id":"8",
                        "parentId":"3",
                        "name":"删除",
                        "type":"button",
                        "link":"delUser",
                        "serviceUrl":"/user/delUser",
                        "description":"删除"
                    }
                ]
            }
        ]
    },
    {
        "id":"74",
        "name":"统计报表",
        "type":"menu",
        "link":"/report",
        "description":"统计报表",
        "children":[
            {
                "id":"75",
                "parentId":"74",
                "name":"市级报表",
                "type":"menu",
                "link":"/cityReport",
                "serviceUrl":"/cityReport",
                "description":"市级报表"
            },
            {
                "id":"76",
                "parentId":"74",
                "name":"每日登记数据统计",
                "type":"menu",
                "link":"/dailyRegister",
                "serviceUrl":"/dailyRegister",
                "description":"每日登记数据统计"
            },
            {
                "id":"77",
                "parentId":"74",
                "name":"每日刷卡统计",
                "type":"menu",
                "link":"/dailyCardFlow",
                "serviceUrl":"/dailyCardFlow",
                "description":"每日刷卡统计"
            }
        ]
    },
    {
        "id":"18",
        "name":"跑步健身",
        "type":"menu",
        "link":"/sports",
        "description":"跑步健身",
        "children":[
            {
                "id":"33",
                "parentId":"18",
                "name":"社区配置",
                "type":"menu",
                "link":"/community",
                "serviceUrl":"/community/queryCommunity",
                "description":"社区配置",
                "children":[
                    {
                        "id":"36",
                        "parentId":"33",
                        "name":"删除",
                        "type":"button",
                        "link":"delCommunity",
                        "serviceUrl":"/community/delCommunity",
                        "description":"删除"
                    },
                    {
                        "id":"34",
                        "parentId":"33",
                        "name":"添加",
                        "type":"button",
                        "link":"addCommunity",
                        "serviceUrl":"/community/addCommunity",
                        "description":"添加"
                    }
                ]
            },
            {
                "id":"38",
                "parentId":"18",
                "name":"学校配置",
                "type":"menu",
                "link":"/school",
                "serviceUrl":"/school/querySchool",
                "description":"学校配置",
                "children":[
                    {
                        "id":"39",
                        "parentId":"38",
                        "name":"添加",
                        "type":"button",
                        "link":"addSchool",
                        "serviceUrl":"/school/addSchool",
                        "description":"添加"
                    },
                    {
                        "id":"40",
                        "parentId":"38",
                        "name":"编辑",
                        "type":"button",
                        "link":"editSchool",
                        "serviceUrl":"/school/editSchool",
                        "description":"编辑"
                    },
                    {
                        "id":"41",
                        "parentId":"38",
                        "name":"删除",
                        "type":"button",
                        "link":"delSchool",
                        "serviceUrl":"/school/delSchool",
                        "description":"删除"
                    },
                    {
                        "id":"42",
                        "parentId":"38",
                        "name":"启用/下架",
                        "type":"button",
                        "link":"enableSchool",
                        "serviceUrl":"/school/enableSchool",
                        "description":"启用/下架"
                    },
                    {
                        "id":"43",
                        "parentId":"38",
                        "name":"导出",
                        "type":"button",
                        "link":"exportSchool",
                        "serviceUrl":"/school/exportSchool",
                        "description":"导出"
                    }
                ]
            },
            {
                "id":"63",
                "parentId":"18",
                "name":"水流管理",
                "type":"menu",
                "link":"/queryTer",
                "serviceUrl":"/ter/queryTer",
                "description":"水流管理",
            },
            {
                "id":"19",
                "parentId":"18",
                "name":"市级配置",
                "type":"menu",
                "link":"/city",
                "serviceUrl":"/city/queryCity",
                "description":"市级配置",
                "children":[
                    {
                        "id":"20",
                        "parentId":"19",
                        "name":"添加",
                        "type":"button",
                        "link":"addCity",
                        "serviceUrl":"/city/addCity",
                        "description":"添加"
                    },
                    {
                        "id":"21",
                        "parentId":"19",
                        "name":"编辑",
                        "type":"button",
                        "link":"editCity",
                        "serviceUrl":"/city/editCity",
                        "description":"编辑"
                    },
                    {
                        "id":"22",
                        "parentId":"19",
                        "name":"删除",
                        "type":"button",
                        "link":"delCity",
                        "serviceUrl":"/city/delCity",
                        "description":"删除"
                    }
                ]
            }
        ]
    }
]
